use store
---Q1 Calculate the number of orders per month in 2018
SELECT 
    MONTHNAME(order_purchase_date) AS month_name,
    COUNT(DISTINCT (order_id)) AS total_orders
FROM
    orders_table
    where year(order_purchase_date)=2018 and order_status not in ('Canceled','Unavailable')
GROUP BY month_name , MONTH(order_purchase_date)
ORDER BY MONTH(order_purchase_date)

---Q2 Find the average number of products per order, grouped by customer city. 

SELECT 
    city, ROUND(AVG(order_qty), 1) AS per_order_qty
FROM
    (SELECT 
        c.customer_city AS city,
            oi.order_id,
            COUNT(oi.product_id) AS order_qty
    FROM
        order_item oi
    JOIN orders_table ot ON oi.order_id = ot.order_id
    JOIN customers c ON ot.customer_id = c.customer_id
    GROUP BY c.customer_city , oi.order_id) AS base1
GROUP BY city
ORDER BY per_order_qty DESC LIMIT 10


---Q3 Calculate the percentage of total revenue contributed by each product category
select category,round((rev/sum(rev) over())*100,1) as rev_percent from
(select p.product_category as category , round(sum(a.product_revenue),2) as rev from
(select oi.order_id, oi.product_id,oi.price, ((oi.price/op.price_value)*ov.total_value) as product_revenue from order_item oi join order_value ov on oi.order_id=ov.order_id  join (SELECT order_id, round(sum(price),2) as price_value from order_item group by order_id) as op on oi.order_id=op.order_id) as a join products p on a.product_id=p.product_id group by p.product_category) as base order by rev_percent desc limit 10
WITH revenue_by_category AS (SELECT p.product_category, SUM(oi.price) AS rev  
FROM order_items oi  
JOIN products p ON oi.product_id = p.product_id  
GROUP BY p.product_category)
SELECT product_category,      
 ROUND(rev,2) AS revenue,       
ROUND(100 * rev / (SELECT SUM(rev) 
FROM revenue_by_category), 2) 
AS pct_total_revenueFROM revenue_by_category
ORDER BY rev DESC;

---Q4 Identify the correlation between product price and the number of times a product has been purchased
SELECT 
        product_id as top_Selling_Product,
            AVG(price) AS avg_price,
            COUNT(product_id) AS purchased_qty
    FROM
        order_item
    GROUP BY product_id order by purchased_qty desc limit 10 

---Q5 Calculate the total revenue generated by each seller, and rank them by revenue
SELECT 
    seller as top10_seller, ROUND(SUM(revenue_by_seller), 2) AS total_rev
FROM
    (SELECT 
        oi.order_id,
            oi.seller_id AS seller,
            (oi.price / b.price_value) * ov.total_value AS revenue_by_seller
    FROM
        order_item oi
    JOIN order_value ov ON oi.order_id = ov.order_id
    JOIN (SELECT 
        order_id, ROUND(SUM(price), 2) AS price_value
    FROM
        order_item
    GROUP BY order_id) AS b ON oi.order_id = b.order_id) AS revenue_generated_by_sellers
GROUP BY seller
ORDER BY total_rev DESC limit 10







